// This file is auto-generated by @hey-api/openapi-ts

export type GetProductsResponse = {
    products?: Array<ProductResponseItem>;
};

export type ProductResponseItem = {
    id: string;
    name: string;
    price: number;
    description: string;
};

export type GetProductsData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/products";
};

export type GetProductsResponses = {
    /**
     * OK
     */
    200: GetProductsResponse;
};

export type GetProductsResponse2 =
    GetProductsResponses[keyof GetProductsResponses];

export type ClientOptions = {
    baseURL: "https://localhost:7249" | (string & {});
};
