// This file is auto-generated by @hey-api/openapi-ts

export type ProductServiceApplicationQueriesProductGetProductsResponse = {
    products?: Array<ProductServiceApplicationQueriesProductProductResponseItem>;
};

export type ProductServiceApplicationQueriesProductProductResponseItem = {
    id?: string;
    name?: string;
    price?: number;
    description?: string;
};

export type ProductServiceApplicationEndpointsProductEndpointsGetProductsEndpointData =
    {
        body?: never;
        path?: never;
        query?: never;
        url: "/api/products";
    };

export type ProductServiceApplicationEndpointsProductEndpointsGetProductsEndpointResponses =
    {
        /**
         * Success
         */
        200: ProductServiceApplicationQueriesProductGetProductsResponse;
    };

export type ProductServiceApplicationEndpointsProductEndpointsGetProductsEndpointResponse =
    ProductServiceApplicationEndpointsProductEndpointsGetProductsEndpointResponses[keyof ProductServiceApplicationEndpointsProductEndpointsGetProductsEndpointResponses];

export type ClientOptions = {
    baseURL: "https://localhost:7249" | (string & {});
};
