// This file is auto-generated by @hey-api/openapi-ts

export type ProductServiceContractsQueriesProductGetProductByIdResponse = {
    id?: string;
    name?: string;
    price?: number;
    description?: string;
};

export type ProductServiceContractsQueriesProductGetProductById = {
    [key: string]: never;
};

export type ProductServiceContractsQueriesProductProductResponseItem = {
    id?: string;
    name?: string;
    price?: number;
};

export type ProductServiceContractsQueriesProductGetProducts = {
    [key: string]: never;
};

export type ProductServiceApplicationEndpointsProductEndpointsGetProductByIdEndpointData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/products/{id}';
};

export type ProductServiceApplicationEndpointsProductEndpointsGetProductByIdEndpointErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type ProductServiceApplicationEndpointsProductEndpointsGetProductByIdEndpointResponses = {
    /**
     * Success
     */
    200: ProductServiceContractsQueriesProductGetProductByIdResponse;
};

export type ProductServiceApplicationEndpointsProductEndpointsGetProductByIdEndpointResponse = ProductServiceApplicationEndpointsProductEndpointsGetProductByIdEndpointResponses[keyof ProductServiceApplicationEndpointsProductEndpointsGetProductByIdEndpointResponses];

export type ProductServiceApplicationEndpointsProductEndpointsGetProductsEndpointData = {
    body?: never;
    path?: never;
    query?: {
        Name?: string | null;
        MinPrice?: number | null;
        MaxPrice?: number | null;
    };
    url: '/api/products';
};

export type ProductServiceApplicationEndpointsProductEndpointsGetProductsEndpointResponses = {
    /**
     * Success
     */
    200: Array<ProductServiceContractsQueriesProductProductResponseItem>;
};

export type ProductServiceApplicationEndpointsProductEndpointsGetProductsEndpointResponse = ProductServiceApplicationEndpointsProductEndpointsGetProductsEndpointResponses[keyof ProductServiceApplicationEndpointsProductEndpointsGetProductsEndpointResponses];

export type ClientOptions = {
    baseURL: 'https://localhost:7249' | (string & {});
};