// This file is auto-generated by @hey-api/openapi-ts

export const RegisterUserSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            nullable: true
        },
        password: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;