// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-axios';
import type { PostAccountRegisterData, PostAccountRegisterError, PostAccountRegisterResponse, } from './types.gen';

export const client = createClient(createConfig());

export const postAccountRegister = <ThrowOnError extends boolean = false>(options?: Options<PostAccountRegisterData, ThrowOnError>) => { return (options?.client ?? client).post<PostAccountRegisterResponse, PostAccountRegisterError, ThrowOnError>({
    ...options,
    url: '/account/register'
}); };