// This file is auto-generated by @hey-api/openapi-ts

export type RegisterUser = {
    email?: (string) | null;
    password?: (string) | null;
};

export type PostAccountRegisterData = {
    body?: RegisterUser;
};

export type PostAccountRegisterResponse = (unknown);

export type PostAccountRegisterError = unknown;

export type GetConnectAuthorizeResponse = (unknown);

export type GetConnectAuthorizeError = unknown;

export type PostConnectAuthorizeResponse = (unknown);

export type PostConnectAuthorizeError = unknown;

export type PostConnectTokenResponse = (unknown);

export type PostConnectTokenError = unknown;