// This file is auto-generated by @hey-api/openapi-ts

export type RegisterUser = {
    email?: (string) | null;
    password?: (string) | null;
};

export type PostAccountRegisterData = {
    body?: RegisterUser;
};

export type PostAccountRegisterResponse = (unknown);

export type PostAccountRegisterError = unknown;